config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :posts
  resources :news
  resources :crews
  get 'crew/index'

  resources :videos
  resources :blogs
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/crew.rb
class Crew < ApplicationRecord
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: [:show, :edit, :update, :destroy]

  # GET /crews
  # GET /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1
  # GET /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  # POST /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: 'Crew was successfully created.' }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1
  # PATCH/PUT /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: 'Crew was successfully updated.' }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1
  # DELETE /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: 'Crew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crew_params
      params.require(:crew).permit(:photo, :name, :bio)
    end
end

app/helpers/crew_helper.rb
module CrewHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/_form.html.erb
<%= form_with(model: crew, local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :crew_photo %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :crew_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :crew_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<body class="gif">
  <div style="background: transparent; width: 90%;  margin:0 auto">
    <div>
      <h1 style="color: white;">Crew</h1>
      <a class="btn btn-primary btn-lg text-light" href="/crews/new" role="button">Ingresar un nuevo miembro al crew</a>
    </div>
    <p></p>
    <p></p>
    <% @crews.each do |crew| %>
      <div class="card" style="width: fill;">
        <img class="card-img-top" src=<%= crew.photo %> alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= crew.name %></h5>
          <p class="card-text"><%= crew.bio %></p>
          <a href="#" class="btn btn-primary"><%= link_to 'Show', crew %></a>
          <a href="#" class="btn btn-primary"><%= link_to 'Edit', edit_crew_path(crew) %></a>
          <a href="#" class="btn btn-primary"><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></a>
        </div>
      </div>
      <p></p>
    <% end %>
  </div>
</body>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @crew.photo %>
</p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @crew.bio %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>